### ISSUE TITLE
Using Window OS and VS 2013

### ISSUE THREAD

**Issue by chethanab16** [NVlabs/intrinsic3d#13]
Hi I am trying to compile  intrinsic 3D using Windows OS and Visual studio 2013 and I compiled the  AppKeyframes successfully in debug mode X64  but when I run the program it will create fusion folder but now extracted keyframes and  the values of sensor_config and sensor_config_fille show  Error reading characters of string as show in the attachment could some one could give some suggestion it would be helpful 
![intrensic-3D_git9](https://user-images.githubusercontent.com/34049539/96102694-c4782180-0f11-11eb-8bc4-d83ed6c2e738.png)
![intrensic-3D_git1](https://user-images.githubusercontent.com/34049539/96103867-25ecc000-0f13-11eb-9ef0-bf81e57efaa3.png)

**Comment by robmaier** [comment]
I would assume that the path to `sensor.yml` and `keyframes.yml` is not correct here (when running from Visual Studio directly)? Either you adjust the path to the `.yml` files or you run it from command line directly in the data folder where the `.yml` files are.

**Comment by chethanab16** [comment]
thankyou so much for your reply when i run .exe from command line directly I am getting the following message as shown in the 1.  image and the path of the .ymlfiles as show in 2. image .

colud you please explain me more about how to adjust  path  or  run it from command line directly in the data folder where the .yml files are.


![intrensic-3D_git2](https://user-images.githubusercontent.com/34049539/96106019-a7455200-0f15-11eb-8184-7b0e5ae0ef06.png)


![intrensic-3D_git3](https://user-images.githubusercontent.com/34049539/96106143-cf34b580-0f15-11eb-995d-d243d989c7a8.png)

**Comment by robmaier** [comment]
To be honest, this does not seem to be an issue related to Intrinsic3D specifically. Since this is hard to debug for me remotely, I would recommend you to ask some colleagues or friends for some debugging help. :)

**Comment by chethanab16** [comment]
@robmaier in my previous comment, i run .exe from command line directly, but I hadn't passed -s=sensor.yml -k=keyframes.yml values and also it was appfusion.exe  but  when I pass run appkeyframes.exe then the following error occurred as in the images , about  sensor.ymlsetting file which is similar when i run from visual studio directly  , could you give me some suggestion .
![intrensic-3D_aookeyframes_16](https://user-images.githubusercontent.com/34049539/96222405-2c3c7400-0fc7-11eb-83ec-04ad9aadcfb1.png)
