### ISSUE TITLE
Error with opencv

### ISSUE THREAD

**Issue by hdeleau** [NVlabs/intrinsic3d#2]
Hi,

I have a compilation error related to libopencv_imgcodecs.
By modifying line 74 (CMakeLists.txt) as follows, the compilation is error-free :
FIND_PACKAGE(OpenCV COMPONENTS core highgui imgproc imgcodecs REQUIRED)

But now, by executing the "../../build/bin/AppKeyframes -s sensor.yml -k keyframes.yml" command, I get the following error: Failed to load settings from file 'true'!

What step could I have forgotten?

Regards

**Comment by robmaier** [comment]
I guess you are using OpenCV3? The command line parser has changed there, something like the following should work:
`../../build/bin/AppKeyframes -s=sensor.yml -k=keyframes.yml`

**Comment by hdeleau** [comment]
Yes, I use OpenCV 3.2 (with Debian Buster).
The new command works perfectly. Thank you.

Regards.

**Comment by robmaier** [comment]
To avoid such confusions in the future, I am going to allow OpenCV3 only. Thanks for your quick feedback and the fix above.

**Comment by chethanab16** [comment]
Hi I am trying to compile intrinsic 3D using Windows OS and Visual studio 2013 and I compiled the AppKeyframes successfully in debug mode X64 but when I run the program it will create fusion folder but now extracted keyframes and the values of sensor_config and sensor_config_fille show Error reading characters of string as show in the attachment could some one could give some suggestion it would be helpful
![intrensic-3D_git9](https://user-images.githubusercontent.com/34049539/96103282-7a437000-0f12-11eb-88f6-752eac04d9d9.png)
![intrensic-3D_git1](https://user-images.githubusercontent.com/34049539/96103790-140b1d00-0f13-11eb-9309-37830be7ed7d.png)
