### ISSUE TITLE
Too Slow

### ISSUE THREAD

**Issue by Buzzroid** [NVlabs/intrinsic3d#7]
AppFusion takes many hours on Windows.
Is it normal?
Don't you use the CUDA?

**Comment by robmaier** [comment]
Did you compile the code in Release mode?
It should probably take ~30 minutes or so, but "many hours" definitely sounds too long.
The code unfortunately runs only on CPU and not on the GPU.

**Comment by chethanab16** [comment]
@Buzzroid I tried to compile the intrinsic 3D using VS 2013 and got stuck at this as shown in the image could you please give me some suggestion .

![intrensic-3D_aookeyframes_15](https://user-images.githubusercontent.com/34049539/96204787-23847780-0fa0-11eb-86dd-5993c566c962.png)
